<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ldap_accounts_ldap_connector'] = 'Учетные записи LDAP соединения';
$lang['ldap_all_networks'] = 'Все сети';
$lang['ldap_app_description'] = 'Механизм LDAP служит общей основой для всех доступных механизмов LDAP включая OpenLDAP и Active Directory.';
$lang['ldap_app_name'] = 'Механизм LDAP';
$lang['ldap_base_dn'] = 'Базовый DN';
$lang['ldap_base_domain'] = 'Основной домен';
$lang['ldap_bind_dn'] = 'Связывающий DN';
$lang['ldap_bind_password'] = 'Bind пароль';
$lang['ldap_capabilities'] = 'Возможности';
$lang['ldap_computers'] = 'Компьютеры';
$lang['ldap_connection_information'] = 'Информация о соединении';
$lang['ldap_containers'] = 'Контейнеры';
$lang['ldap_directory_information'] = 'Информация о каталоге';
$lang['ldap_directory_status'] = 'Состояние каталога';
$lang['ldap_importing_data'] = 'Импорт данных.';
$lang['ldap_ldap_is_offline'] = 'LDAP оффлайн.';
$lang['ldap_ldap_operation_failed'] = 'LDAP операция не удалась.';
$lang['ldap_local_network'] = 'Локальная сеть';
$lang['ldap_master'] = 'Главный';
$lang['ldap_mode'] = 'Режим';
$lang['ldap_not_published'] = 'Не опубликован';
$lang['ldap_preparing_import'] = 'Подготовка к импорту.';
$lang['ldap_publish_policy'] = 'Публичная политика';
$lang['ldap_shutting_down_ldap_server'] = 'Выключение LDAP сервера.';
$lang['ldap_slave'] = 'Ведомый';
$lang['ldap_standalone'] = 'Автономный';
