<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ldap_accounts_ldap_connector'] = 'Łącznik kont LDAP';
$lang['ldap_all_networks'] = 'Wszystkie sieci';
$lang['ldap_app_description'] = 'Silnik LDAP dostarcza wspólny framework dla wszystkich dostępnych implementacji LDAP włączając w to OpenLDAP oraz Active Directory.';
$lang['ldap_app_name'] = 'Silnik LDAP';
$lang['ldap_base_dn'] = 'Podstawowy DN';
$lang['ldap_base_domain'] = 'Domena podstawowa';
$lang['ldap_bind_dn'] = 'Łączący DN';
$lang['ldap_bind_password'] = 'Hasło łączące';
$lang['ldap_capabilities'] = 'Możliwości';
$lang['ldap_computers'] = 'Komputery';
$lang['ldap_connection_information'] = 'Informacje o połączeniu';
$lang['ldap_containers'] = 'Kontenery';
$lang['ldap_directory_information'] = 'Informacje o usłudze katalogowej';
$lang['ldap_directory_status'] = 'Stan usługi katalogowej';
$lang['ldap_importing_data'] = 'Importowanie danych.';
$lang['ldap_ldap_is_offline'] = 'LDAP jest offline.';
$lang['ldap_ldap_operation_failed'] = 'Operacja LDAP nieudała się.';
$lang['ldap_local_network'] = 'Sieć lokalna';
$lang['ldap_master'] = 'Nadrzędny';
$lang['ldap_mode'] = 'Tryb';
$lang['ldap_not_published'] = 'Nie opublikowany';
$lang['ldap_preparing_import'] = 'Przygotowywanie importu.';
$lang['ldap_publish_policy'] = 'Reguła publikacji';
$lang['ldap_shutting_down_ldap_server'] = 'Wyłączanie serwera LDAP.';
$lang['ldap_slave'] = 'Podrzędny';
$lang['ldap_standalone'] = 'Samodzielny';
